### ISSUE TITLE
Bug: Tranquillien Reputation Duplicated

### ISSUE THREAD

**Issue by LadySpibe** [wowtrack/feedback#44]
**Describe the bug**
The [reputation tracker](https://wowtrack.gg/reputation/tracker) lists Tranquillien 406 times. This occurs both when logged in, and when not logged in.

**Expected behavior**
As with the other Reputations, Tranquillien should only be listed once.

**Screenshots**
![5LXUPkiRAA](https://github.com/wowtrack/feedback/assets/94585785/1bf99382-95f5-42b9-9cc5-ad12935e6385)
![firefox_X1moMUU26v](https://github.com/wowtrack/feedback/assets/94585785/16ce8313-f919-4b6d-9dd0-ea8cae1344a7)

**Debug Data**
Paste debug data from "Create Bug Report" tool from [profile page](https://wowtrack.gg/account/profile):

[wowtrack debug data.txt](https://github.com/wowtrack/feedback/files/15277834/wowtrack.debug.data.txt)

**Comment by bonesoul** [comment]
thanks for the report, will fix it.

**Comment by bonesoul** [comment]
fixed the issue in development branch, should be good within next live release.
